export const SIGN_IN = "SIGN_IN";
export const SIGN_UP = "SIGN_UP";
export const ADD_BASIC_DETAIL = "ADD_BASIC_DETAIL";
export const ADD_EXPERIENCE = "ADD_EXPERIENCE";
export const EDIT_EXPERIENCE = "EDIT_EXPERIENCE";
export const LOAD_USER_BASIC_DETAILS = "LOAD_USER_BASIC_DETAILS";
export const LOAD_USER_EXP_DETAILS = "LOAD_USER_EXP_DETAILS";